languageCode = "en-us"
title = "Massively"
baseURL = "https://hugo-theme-massively.netlify.com/"
theme = "../.."
googleanalytics = "UA-113904582-4"

# [params]
  # set below parameter to define a favicon
  # favicon = "favicon.ico"

# Below parameters can be set to override default post settings
# [params.posts]
#     foldername = "post"
#     pagesize = "6"
#     featuredpost = "true"

[params.settings]
    disqus = "hugo-massively"

[languages]
[languages.en]
  languageName = "English"
[languages.es]
  languageName = "Español"
  title = "Massively - Versión Español"
